import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export async function generateClothedImage(
  clothingBase64: string,
  clothingMimeType: string,
  personBase64: string,
  personMimeType: string
): Promise<string> {
  try {
    // A more specific prompt that clearly identifies each image's role.
    const prompt = `The first image contains an article of clothing. The second image contains a person. Generate a new, photorealistic image of the person from the second image wearing the clothing from the first image. The background should be a plain, smooth white, with soft, natural lighting.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          // Sending images before the prompt can improve model performance.
          {
            inlineData: {
              data: clothingBase64,
              mimeType: clothingMimeType,
            },
          },
          {
            inlineData: {
              data: personBase64,
              mimeType: personMimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return part.inlineData.data;
        }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Gemini API call failed:", error);
    throw new Error("Failed to generate image. The model may have refused the request. Please try with different images.");
  }
}
