import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY: string = (import.meta.env.VITE_GEMINI_API_KEY as string | undefined) ?? "";

function getAi(): GoogleGenAI {
  if (!API_KEY) {
    throw new Error(
      "Gemini API key is not set. Create a .env.local file in the project root with VITE_GEMINI_API_KEY=<your key>, then restart the dev server."
    );
  }
  return new GoogleGenAI({ apiKey: API_KEY });
}

export async function generateClothedImage(
  clothingBase64: string,
  clothingMimeType: string,
  personBase64: string,
  personMimeType: string
): Promise<string> {
  try {
    // A more direct prompt to clearly guide the model and avoid safety filters.
    const prompt = `Place the clothing from the first image onto the person in the second image. Create a photorealistic image with a smooth white background and natural lighting.`;

    const response = await getAi().models.generateContent({
      model: 'gemini-2.5-flash-image',
      // FIX: The 'contents' property must be an array of Content objects.
      contents: [{
        parts: [
          {
            inlineData: {
              data: clothingBase64,
              mimeType: clothingMimeType,
            },
          },
          {
            inlineData: {
              data: personBase64,
              mimeType: personMimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      }],
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          return part.inlineData.data;
        }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Gemini API call failed:", error);
    throw new Error("Failed to generate image. The model may have refused the request. Please try with different images.");
  }
}
